version: "3"
services: 
  neo4j:
    image: neo4j:4.3.2
    environment:
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true 
      - NEO4J_apoc_import_file_enabled=true 
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=\[\"apoc\"\] 
    ports:
      - "7474:7474"
      - "1337:1337"
      - "7687:7687"
    volumes:
      - ./logs:/logs
      - ./conf:/conf
      - ./data/import:/var/lib/neo4j/import
      - ./data/db:/data
      - ./plugins:/plugins

  notebook:
    image: cbleker/jupyter-graph-notebook:latest
    ports:
      - "8888:8888"
    links:
      - neo4j:neo4j
    volumes:
      - ./examples:/home/jovyan/examples
      - ./work:/home/jovyan/work
      - ./data:/home/jovyan/data
    environment: 
      - NB_UID=7474
      - NB_GID=7474
    user: root
