services:

  neo4j:
    build:
      context: .
    env_file:
      - .env # used inside container
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/conf:/conf
      - ./neo4j_db/data/import:/import
      - ./neo4j_db/data/db:/data
      - ./neo4j_db/plugins:/plugins
