version: "3"
services: 
  neo4j:
    image: skm-graph-dev
    build: 
        context: .
        dockerfile: Dockerfile-dev
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "1337:1337"
      - "7687:7687"
    volumes:
      - ./logs:/logs
      - ./conf:/conf
      - ./data/import:/var/lib/neo4j/import
      - ./data/db:/data

  notebook:
    image: cbleker/jupyter-graph-notebook:latest
    ports:
      - "8889:8888"
    links:
      - neo4j:neo4j
    volumes:
      - ./work:/home/jovyan/work
      - ./data:/home/jovyan/data
